# Generated by Django 4.1.5 on 2023-01-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='The_best_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(default=None, max_length=250, verbose_name='Заголовок')),
                ('slug', models.SlugField(null=True)),
                ('content', models.TextField(null=True, verbose_name='Содержимое')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Изображение (превью)')),
                ('date_of_creation', models.DateField(auto_now_add=True, null=True, verbose_name='Created Time')),
                ('sign_of_publication', models.CharField(choices=[('1', 'опубликован'), ('0', 'не опубликован')], default='0', max_length=10)),
                ('numbers_of_views', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоки',
            },
        ),
    ]
