# Generated by Django 4.1.5 on 2023-01-31 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='the_best_blog',
            options={'verbose_name': 'блог', 'verbose_name_plural': 'блоги'},
        ),
        migrations.AlterField(
            model_name='the_best_blog',
            name='sign_of_publication',
            field=models.CharField(choices=[('1', 'опубликован'), ('0', 'не опубликован')], default='0', max_length=20),
        ),
    ]
