# Generated by Django 4.1.6 on 2023-02-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_the_best_blog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='the_best_blog',
            options={'verbose_name': 'блогuu', 'verbose_name_plural': 'блоги'},
        ),
    ]
