# Generated by Django 4.1.5 on 2023-01-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=1998, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
