# Generated by Django 4.1.6 on 2023-02-25 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_author_product_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author_create',
        ),
    ]
