# Generated by Django 4.1.6 on 2023-02-12 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_version_name_of_version_alter_version_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(max_length=29, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.category'),
        ),
    ]
