# Generated by Django 4.1.6 on 2023-02-25 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'permissions': (('change_status', 'can change status'), ('change_info', 'can change info'), ('change_category', 'can change category')), 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
